### ISSUE TITLE
Move to song.link API

### ISSUE THREAD

**Issue by bukhalo** [streaming-hell/streaming-hell#47]
Good news everyone, [song.link](song.link) published [public API and docs](https://github.com/songlink/docs). Also, song.link developer @kweiberth provided API key for us (thx 😍).

Now need to get rid of parsing song.link pages and use thier API.

**Comment by kweiberth** [comment]
Let me know if I can help or if you have any issues or feedback as you implement the API.

**Comment by bukhalo** [comment]
Suspended until https://github.com/streaming-hell/backend/issues/4 task completion, @tafler

**Comment by bukhalo** [comment]
Same task for [vk-bot](https://github.com/streaming-hell/vk-bot/), https://github.com/streaming-hell/vk-bot/issues/3

**Comment by bukhalo** [comment]
Implemented in #154
